// Google Gemini Structured Output - Core Constants and Schemas
// Shared definitions used across all entity generation modules

import { GEMINI_CONFIG } from '../../config/gemini.config'
import type { Rarity } from '../../types/base.types'

// API Configuration
export const STRUCTURED_FLASH_LITE_MODEL = GEMINI_CONFIG.models.flashLite
export const STRUCTURED_IMAGE_MODEL = GEMINI_CONFIG.models.flashImage
export const STRUCTURED_API_BASE_URL = GEMINI_CONFIG.apiBase

// JSON Schema for Item entities
export const ITEM_SCHEMA = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      description:
        "Optional ID field - will be auto-generated by the system if not provided",
    },
    name: { type: 'string', description: 'Display name of the item' },
    rarity: {
      type: 'string',
      enum: ['common', 'rare', 'epic', 'legendary'] as Rarity[],
      description:
        "Significance level: 'common' = everyday/ordinary, 'rare' = quality/notable, 'epic' = famous/major, 'legendary' = iconic/world-famous",
    },
    description: { type: 'string', description: 'Detailed historical description' },
    category: {
      type: 'string',
      enum: [] as string[], // Will be populated dynamically
      description: 'Item category',
    },
  },
  required: ['name', 'rarity', 'description'],
}

// JSON Schema for NPC entities
export const NPC_SCHEMA = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      description:
        "Optional ID field - will be auto-generated by the system if not provided",
    },
    name: { type: 'string', description: 'Display name of the NPC' },
    rarity: {
      type: 'string',
      enum: ['common', 'rare', 'epic', 'legendary'] as Rarity[],
      description:
        "Significance level: 'common' = everyday/ordinary, 'rare' = quality/notable, 'epic' = famous/major, 'legendary' = iconic/world-famous",
    },
    description: { type: 'string', description: 'Detailed historical description' },
    category: {
      type: 'string',
      enum: [] as string[], // Will be populated dynamically
      description: 'NPC category',
    },
  },
  required: ['name', 'rarity', 'description'],
}

// JSON Schema for Location entities
export const LOCATION_SCHEMA = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      description:
        "Optional ID field - will be auto-generated by the system if not provided",
    },
    name: { type: 'string', description: 'Display name of the location' },
    rarity: {
      type: 'string',
      enum: ['common', 'rare', 'epic', 'legendary'] as Rarity[],
      description:
        "Significance level: 'common' = everyday/ordinary, 'rare' = quality/notable, 'epic' = famous/major, 'legendary' = iconic/world-famous",
    },
    description: { type: 'string', description: 'Detailed historical description' },
    category: {
      type: 'string',
      enum: [] as string[], // Will be populated dynamically
      description: 'Location category',
    },
  },
  required: ['name', 'rarity', 'description'],
}

